<div class="news__body">
    <div class="news__item">
        <img src="<?= $this->getViewFileUrl('Magento_Cms::images/news/news_1.png'); ?>" alt=""/>
        <div class="news__info">
            <p class="news__title">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
            <p class="news__subtitle">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and</p>
            <a href="">more</a>
        </div>
        
    </div>
    <div class="news__item">
        <img src="<?= $this->getViewFileUrl('Magento_Cms::images/news/news_2.png'); ?>" alt=""/>
        <div class="news__info">
            <p class="news__title">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
            <p class="news__subtitle">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and</p>
            <a href="">more</a>
        </div>
    </div>
</div>