<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="footer__info">
    <div class="footer__block">
        <ul>
            <li class="footer__title">Browse Basecamp</li>
            <li>about us</li>
            <li>basecamp gift vouchers</li>
            <li>basecamp membership</li>
            <li>advanced search</li>
            <li>group sale & bulk orders</li>
            <li>jobs- sitemap</li>
            <li>contact us</li>
            <li>dublin simon community</li>
            <li>camino kit list</li>
        </ul>
        <ul>
            <li class="footer__title">stay connected</li>
            <li></li>
            <li></li>
            <li></li>
        </ul>
    </div>

    <div class="footer__block">
        <ul>
            <li class="footer__title">my account</li>
            <li>sign in</li>
            <li>account settings</li>
            <li>view cart</li>
            <li>my wishlist</li>
            <li>my compared products</li>
        </ul>

        <ul>
            <li class="footer__title">we accept</li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>
    </div>

    <div class="footer__block">
        <ul>
            <li class="footer__title">terms and conditions</li>
            <li>customer service</li>
            <li>shipping method</li>
            <li>delivery</li>
            <li>return policy</li>
            <li>payment information</li>
            <li>environmetal responsibility</li>
            <li>privacy policy</li>
            <li>privacy statement</li>
        </ul>
    </div>

    <div class="footer__block">
        <ul>
            <li class="footer__title">we are located at:</li>
            <li>dublin address</li>
            <li>basecamp 108-109</li>
            <li>middle abbey street</li>
            <li>dublin 1</li>
            <li> </li>
            <li>telephone: +353 1 443 0800</li>
            <li>email: info@basecamp.ie</li>
            <li> </li>
            <li>kilkenny address</li>
            <li>basecamp 79 high st, kilkenny</li>
            <li> </li>
            <li>telephone: +353 56 775 6356</li>
            <li>email: kilkenny@basecamp.ie</li>
        </ul>
    </div>
</div>