<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="footer__info container-fluid">
    <div class="row">
        <div class="footer__block col-md-6 col-lg-3">
            <ul>
                <li class="footer__title">Browse Basecamp</li>
                <li>about us</li>
                <li>basecamp gift vouchers</li>
                <li>basecamp membership</li>
                <li>advanced search</li>
                <li>group sales & bulk orders</li>
                <li>jobs- sitemap</li>
                <li>contact us</li>
                <li>dublin simon community</li>
                <li>camino kit list</li>
            </ul>
            <ul>
                <li class="footer__title">stay connected</li>
                <li><img src="<?= $this->getViewFileUrl('Magento_Theme::images/connect.png'); ?>" alt=""></li>
            </ul>
        </div>

        <div class="footer__block col-md-6 col-lg-3">
            <ul>
                <li class="footer__title">my account</li>
                <li>sign in</li>
                <li>account settings</li>
                <li>view cart</li>
                <li>my wishlist</li>
                <li>my compared products</li>
            </ul>

            <ul>
                <li class="footer__title" style="margin-bottom: 10px;">we accept</li>
                <li><img src="<?= $this->getViewFileUrl('Magento_Theme::images/payment.png'); ?>" alt=""></li>
            </ul>
        </div>

        <div class="footer__block col-md-6 col-lg-3">
            <ul>
                <li class="footer__title">terms and conditions</li>
                <li>customer service</li>
                <li>shipping method</li>
                <li>delivery</li>
                <li>returns policy</li>
                <li>payment information</li>
                <li>environmetal responsibility</li>
                <li>privacy policy</li>
                <li>privacy statement</li>
            </ul>
        </div>

        <div class="footer__block col-md-6 col-lg-3">
            <ul>
                <li class="footer__title">we are located at:</li>
                <li style="text-transform: uppercase;">dublin address</li>
                <li>basecamp 108 -109</li>
                <li>middle abbey street</li>
                <li>dublin 1</li>
                <li>&nbsp;</li>
                <li>telephone: +353 1 443 0800</li>
                <li>email: info@basecamp.ie</li>
                <li class="line-bottom"></li>
                <li><b>kilkenny address</b></li>
                <li>basecamp 79 high st, kilkenny</li>
                <li>&nbsp;</li>
                <li>telephone: +353 56 775 6356</li>
                <li>email: kilkenny@basecamp.ie</li>
            </ul>
        </div>
    </div><!-- row -->

    <div class="row">
        <div class="col copyright">
            <img src="<?= $this->getViewFileUrl('Magento_Theme::images/copyright.png'); ?>" alt="">
            <p>© 2017 basecamp.ie. All Rights Reserved.</p>
        </div>
    </div>
</div>