<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit)
?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <li class="level0 category-item level-top ui-menu-item">
            <a href="<?= $block->getBaseUrl() ?>" class="level-top"><span>Home</span></a>
        </li>
        <?= /* @noEscape */ $_menuHtml ?>
        <li class="level0 category-item level-top ui-menu-item">
            <a href="#" class="level-top"><span>Voucher</span></a>
        </li>
        <li class="level0 category-item level-top ui-menu-item">
            <a href="#" class="level-top"><span>Brand</span></a>
        </li>
        <li class="level0 category-item level-top ui-menu-item">
            <a href="<?= $block->getUrl('contact') ?>" class="level-top"><span>Contact us</span></a>
        </li>
        <?= $block->getChildHtml() ?>
    </ul>
</nav>

<div class="promotion">
    <ul>
        <li>
            <img src="<?= $this->getViewFileUrl('Magento_Theme::images/ireland_flag.png'); ?>" alt="" />
            <span><b>Free</b> Delivery in Ireland on Orders Over €30</span>
        </li>
        <li>
            <img src="<?= $this->getViewFileUrl('Magento_Theme::images/circular_arrows.png'); ?>" alt="" />
            <span>Easy and Hassle Free Return</span>
        </li>
        <li>
            <img src="<?= $this->getViewFileUrl('Magento_Theme::images/ribbon.png'); ?>" alt="" />
            <span>1 Year Limited Warranty</span>
        </li>
        <li>
            <img src="<?= $this->getViewFileUrl('Magento_Theme::images/transport.png'); ?>" alt="" />
            <span>Fast Tracked Delivery</span>
        </li>
    </ul>
</div>