<div class="footer__info container-fluid">
    <div class="row">
        <div class="footer__block block__1 col-sm-6 col-lg col-xxl-3">
            <ul class="browse">
                <li class="footer__title">Browse Basecamp</li>
                <li><a href="#" class="footer-link">about us</a></li>
                <li><a href="#" class="footer-link">basecamp gift vouchers</a></li>
                <li><a href="#" class="footer-link">basecamp membership</a></li>
                <li><a href="#" class="footer-link">advanced search</a></li>
                <li><a href="#" class="footer-link">group sales & bulk orders</a></li>
                <li><a href="#" class="footer-link">jobs- sitemap</a></li>
                <li><a href="#" class="footer-link">contact us</a></li>
                <li><a href="#" class="footer-link">dublin simon community</a></li>
                <li><a href="#" class="footer-link">camino kit list</a></li>
            </ul>
            <ul class="connect">
                <li class="footer__title">stay connected</li>
                <li><img src="<?= $this->getViewFileUrl('Magento_Theme::images/connect.png'); ?>" alt=""></li>
            </ul>
        </div>

        <div class="footer__block block__2 col-sm-6 col-lg col-xxl-2">
            <ul class="account">
                <li class="footer__title">my account</li>
                <li><a href="#" class="footer-link">sign in</a></li>
                <li><a href="#" class="footer-link">account settings</a></li>
                <li><a href="#" class="footer-link">view cart</a></li>
                <li><a href="#" class="footer-link">my wishlist</a></li>
                <li><a href="#" class="footer-link">my compared products</a></li>
            </ul>

            <ul class="accept">
                <li class="footer__title" style="margin-bottom: 10px;">we accept</li>
                <li><img src="<?= $this->getViewFileUrl('Magento_Theme::images/payment.png'); ?>" alt=""></li>
            </ul>
        </div>

        <div class="footer__block block__3 col-sm-6 col-lg col-xxl-3">
            <ul class="term">
                <li class="footer__title">terms and conditions</li>
                <li><a href="#" class="footer-link">customer service</a></li>
                <li><a href="#" class="footer-link">shipping method</a></li>
                <li><a href="#" class="footer-link">delivery</a></li>
                <li><a href="#" class="footer-link">returns policy</a></li>
                <li><a href="#" class="footer-link">payment information</a></li>
                <li><a href="#" class="footer-link">environmetal responsibility</a></li>
                <li><a href="#" class="footer-link">privacy policy</a></li>
                <li><a href="#" class="footer-link">privacy statement</a></li>
            </ul>
        </div>

        <div class="footer__block block__4 col-sm-6 col-lg col-xxl">
            <ul class="locate">
                <li class="footer__title">we are located at:</li>
                <li style="text-transform: uppercase;">dublin address</li>
                <li>basecamp 108 -109</li>
                <li>middle abbey street</li>
                <li>dublin 1</li>
                <li>&nbsp;</li>
                <li>telephone: +353 1 443 0800</li>
                <li>email: info@basecamp.ie</li>
                <li class="line-bottom"></li>
                <li><b>kilkenny address</b></li>
                <li>basecamp 79 high st, kilkenny</li>
                <li>&nbsp;</li>
                <li>telephone: +353 56 775 6356</li>
                <li>email: <span style="text-transform: lowercase;">kilkenny@basecamp.ie</span></li>
            </ul>
        </div>
    </div><!-- row -->

    <div class="row">
        <div class="col copyright">
            <img src="<?= $this->getViewFileUrl('Magento_Theme::images/copyright.png'); ?>" alt="">
            <p>© 2017 basecamp.ie. All Rights Reserved.</p>
        </div>
    </div>
</div>