<div class="banner__offer">
    <div class="banner__items"><img src="<?= $this->getViewFileUrl('Magento_Cms::images/summer_offer.png'); ?>" alt="">
        <div class="banner__content summer__offer">
            <p class="banner__title">summer offers</p>
        </div>
    </div>
    <div class="banner__items"><img src="<?= $this->getViewFileUrl('Magento_Cms::images/holiday_offer.png'); ?>" alt="">
        <div class="banner__content holiday__offer">
            <p class="banner__title">holiday offers</p>
            <p class="banner__subtitle">explore now</p>
        </div>
    </div>
</div>