<div class="banner__profit">
    <div class="banner__content profit__img">
        <div class="banner__items"><img src="<?= $this->getViewFileUrl('Magento_Cms::images/Layer_17.png'); ?>" alt="">
            <p class="profit__content">camping</p>
        </div>
    </div>
    <div class="banner__content profit__img">
    <div class="banner__items"><img src="<?= $this->getViewFileUrl('Magento_Cms::images/Layer_18.png'); ?>" alt="">
            <p class="profit__content">hiking</p>
        </div>
    </div>
    <div class="banner__content profit__img">
    <div class="banner__items"><img src="<?= $this->getViewFileUrl('Magento_Cms::images/Layer_19.png'); ?>" alt="">
            <p class="profit__content">packs</p>
        </div>
    </div>
    <div class="banner__content profit__img">
    <div class="banner__items"><img src="<?= $this->getViewFileUrl('Magento_Cms::images/Layer_20.png'); ?>" alt="">
            <p class="profit__content">climbing</p>
        </div>
    </div>
    <div class="banner__content profit__img">
    <div class="banner__items"><img src="<?= $this->getViewFileUrl('Magento_Cms::images/Layer_21.png'); ?>" alt="">
            <p class="profit__content">fitness</p>
        </div>
    </div>
</div>