<div class="banner__service">
    <div class="banner__items"><img src="<?= $this->getViewFileUrl('Magento_Cms::images/Layer_24.png'); ?>" alt="">
        <div class="banner__content half__price">
            <p class="banner__title">half price</p>
        </div>
    </div>
    <div class="banner__items"><img src="<?= $this->getViewFileUrl('Magento_Cms::images/Layer25.png'); ?>" alt="">
        <div class="banner__content ruck__sack">
            <p class="banner__title">ruck sack</p>
            <p class="banner__subtitle">offer price</p>
        </div>
    </div>
    <div class="banner__items"><img src="<?= $this->getViewFileUrl('Magento_Cms::images/Layer26.png'); ?>" alt="">
        <div class="banner__content climbing__equipment">
            <p class="banner__subtitle">buy now</p>
        </div>
    </div>
</div>